services:
  - type: web
    name: maharashtra-tour-guide-backend
    env: node
    buildCommand: |
      npm install
      npm install -g autoprefixer postcss tailwindcss @tailwindcss/typography
      npm install -D autoprefixer postcss tailwindcss @tailwindcss/typography
      npm run build
    startCommand: NODE_ENV=production node dist/index.js
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false # This will need to be manually set in the Render dashboard
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: 'true' 